"""empty message

Revision ID: 052b1a5bc197
Revises: caf4d411ef9d
Create Date: 2023-04-11 15:48:42.977255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052b1a5bc197'
down_revision = 'caf4d411ef9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_milking_periods', sa.Column('animal_box', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animal_milking_periods', 'animal_box')
    # ### end Alembic commands ###
