"""empty message

Revision ID: 13eb0c35774b
Revises: 052b1a5bc197
Create Date: 2023-04-13 08:37:18.978578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13eb0c35774b'
down_revision = '052b1a5bc197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animal_milking_periods', 'animal_box')
    op.add_column('animals', sa.Column('animal_box', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animals', 'animal_box')
    op.add_column('animal_milking_periods', sa.Column('animal_box', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
