"""empty message

Revision ID: 173d34a360f4
Revises: 4cde42186463
Create Date: 2023-01-20 12:37:20.549356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '173d34a360f4'
down_revision = '4cde42186463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milkings_per_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date_recorded', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('milkings_per_day')
    # ### end Alembic commands ###
