"""empty message

Revision ID: 2080267fe550
Revises: a820117c5961
Create Date: 2023-01-30 09:21:19.885323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2080267fe550'
down_revision = 'a820117c5961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uniqueDateTimeMilking', 'milkings', ['animal_id', 'days_from_last_birth', 'milking_time'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uniqueDateTimeMilking', 'milkings', type_='unique')
    # ### end Alembic commands ###
