"""empty message

Revision ID: 2585dd9e59fe
Revises: 4f37e3930dd5
Create Date: 2023-01-09 08:35:47.503111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2585dd9e59fe'
down_revision = '4f37e3930dd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_alerts', sa.Column('date_recorded', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animal_alerts', 'date_recorded')
    # ### end Alembic commands ###
