"""empty message

Revision ID: 4f37e3930dd5
Revises: f8a5ccf5a938
Create Date: 2023-01-05 21:32:24.054726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f37e3930dd5'
down_revision = 'f8a5ccf5a938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milkings', sa.Column('milking_period', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_milkings_milking_period'), 'milkings', ['milking_period'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_milkings_milking_period'), table_name='milkings')
    op.drop_column('milkings', 'milking_period')
    # ### end Alembic commands ###
