"""empty message

Revision ID: 89b74660a22c
Revises: 298ede5cc283
Create Date: 2023-01-12 10:05:41.420274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b74660a22c'
down_revision = '298ede5cc283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal_milking_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('milking_period', sa.Integer(), nullable=True),
    sa.Column('start_of_milking_period', sa.Date(), nullable=False),
    sa.Column('end_of_milking_period', sa.Date(), nullable=True),
    sa.Column('has_child', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('animal_births', 'milking_period')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_births', sa.Column('milking_period', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('animal_milking_periods')
    # ### end Alembic commands ###
