"""empty message

Revision ID: a26132378a47
Revises: 
Create Date: 2023-01-05 20:59:32.418493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a26132378a47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'animal_births', ['child_id'])
    op.add_column('milkings', sa.Column('days_from_last_birth', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milkings', 'days_from_last_birth')
    op.drop_constraint(None, 'animal_births', type_='unique')
    # ### end Alembic commands ###
