"""empty message

Revision ID: a820117c5961
Revises: fca260532ee4
Create Date: 2023-01-25 19:57:30.008036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a820117c5961'
down_revision = 'fca260532ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milkings_per_day', sa.Column('num_of_animals_milked', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milkings_per_day', 'num_of_animals_milked')
    # ### end Alembic commands ###
