"""empty message

Revision ID: caf4d411ef9d
Revises: 2080267fe550
Create Date: 2023-02-08 18:32:29.911255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf4d411ef9d'
down_revision = '2080267fe550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('milkings_per_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date_recorded', sa.Date(), nullable=False),
    sa.Column('num_of_animals_milked', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_recorded')
    )
    op.create_table('animal_milking_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('milking_period', sa.Integer(), nullable=True),
    sa.Column('start_of_milking_period', sa.Date(), nullable=False),
    sa.Column('end_of_milking_period', sa.Date(), nullable=True),
    sa.Column('has_child', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('milkings', sa.Column('days_from_last_birth', sa.Integer(), nullable=True))
    op.add_column('milkings', sa.Column('milking_time', sa.String(length=60), nullable=True))
    op.add_column('milkings', sa.Column('milking_period', sa.Integer(), nullable=True))
    op.add_column('milkings', sa.Column('change_from_last_milking', sa.Float(), nullable=True))
    op.add_column('milkings', sa.Column('total_milk_up_to_today', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_milkings_milking_period'), 'milkings', ['milking_period'], unique=False)
    op.create_index(op.f('ix_milkings_milking_time'), 'milkings', ['milking_time'], unique=False)
    op.create_unique_constraint('uniqueDateTimeMilking', 'milkings', ['animal_id', 'days_from_last_birth', 'milking_time'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uniqueDateTimeMilking', 'milkings', type_='unique')
    op.drop_index(op.f('ix_milkings_milking_time'), table_name='milkings')
    op.drop_index(op.f('ix_milkings_milking_period'), table_name='milkings')
    op.drop_column('milkings', 'total_milk_up_to_today')
    op.drop_column('milkings', 'change_from_last_milking')
    op.drop_column('milkings', 'milking_period')
    op.drop_column('milkings', 'milking_time')
    op.drop_column('milkings', 'days_from_last_birth')
    op.drop_table('animal_milking_periods')
    op.drop_table('milkings_per_day')
    # ### end Alembic commands ###
