"""empty message

Revision ID: e33f42227ced
Revises: 89b74660a22c
Create Date: 2023-01-16 12:00:21.107973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e33f42227ced'
down_revision = '89b74660a22c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milkings', sa.Column('change_from_last_milking', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milkings', 'change_from_last_milking')
    # ### end Alembic commands ###
