"""empty message

Revision ID: f8a5ccf5a938
Revises: a26132378a47
Create Date: 2023-01-05 21:09:05.371972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8a5ccf5a938'
down_revision = 'a26132378a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animal_births', sa.Column('milking_period', sa.Integer(), nullable=True))
    op.add_column('milkings', sa.Column('milking_time', sa.String(length=60), nullable=True))
    op.create_index(op.f('ix_milkings_milking_time'), 'milkings', ['milking_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_milkings_milking_time'), table_name='milkings')
    op.drop_column('milkings', 'milking_time')
    op.drop_column('animal_births', 'milking_period')
    # ### end Alembic commands ###
