"""empty message

Revision ID: fca260532ee4
Revises: 173d34a360f4
Create Date: 2023-01-20 12:39:36.429049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca260532ee4'
down_revision = '173d34a360f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'milkings_per_day', ['date_recorded'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'milkings_per_day', type_='unique')
    # ### end Alembic commands ###
